LIBOBJ += $(patsubst %, timestepping/%, sdc.o)

# # unit test targets
# sdc: sdc.cpp sdc.hh
# 	$(CXX) $(WFLAGS) $(DEBUGFLAGS) $(INCLUDE) -DUNITTEST $< $(DUNELIB) $(BOOSTLIB) $(BLASLIB) $(FTNLIB) -o $@
# 
