
TUTORIALTARGETS += run-covid_germany_abm_pde_ode-tutorial
TUTORIALTARGETS += build-covid_germany_abm_pde_ode-tutorial
TUTORIALRUNTARGETS +=

FILE ?= covid

DEPENDSRC += tutorial/covid_germany_abm_pde_ode/$(FILE).cpp

.PHONY: build-covid_germany_abm_pde_ode-tutorial
build-covid_germany_abm_pde_ode-tutorial: tutorial/covid_germany_abm_pde_ode/$(FILE)

.PHONY: run-covid_germany_abm_pde_ode-tutorial
run-covid_germany_abm_pde_ode-tutorial: tutorial/covid_germany_abm_pde_ode/$(FILE)
	cd tutorial/covid_germany_abm_pde_ode; ./$(FILE)
tutorial/covid_germany_abm_pde_ode/$(FILE): tutorial/covid_germany_abm_pde_ode/$(FILE).o #tutorial/covid_germany_abm_pde_ode/$(FILE).o
	$(CXX) $(FLAGS) $< $(KASKADE7)/libs/*.o /opt/yaml-cpp-kaskade/lib/libyaml-cpp.a $(KASKADELIB) \
	$(DUNELIB) \
	$(UGLIB) \
	$(BOOSTLIB) \
	$(DIRECTSOLVERLIB) \
	$(ITSOLLIB) \
	$(HYPRELIB) \
	$(AMIRALIB) \
	$(BLASLIB) $(FTNLIB) $(NUMALIB) $(LINKFLAGS) -lz -o $@

